name: Docker Image build & sonar-scan

on:
  push:
    branches: [ master ] #main
  pull_request:
    branches: [ master ] #main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag highbyte/sonarscan-dotnet:$(date +%s) #buildしてbinariesを作る
#ここまでOK
    - name: Setup sonarqube　
      uses: warchant/setup-sonar-scanner@v3 #https://github.com/marketplace/actions/sonar-scannerを採用
    - name: Run sonarqube
    #  env:
    # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.login=e7f69a4fa46e282022d13886ec6a7bf7af4fa215
           -Dsonar.organization=yjp
           -Dsonar.host.url=https://sonarcloud.io/
           -Dsonar.projectKey=sonar-scanner-action
